### ISSUE TITLE
File exists but it's empty

### ISSUE THREAD

**Issue by alexgarcia9425** [nbesli/pdf-merger-js#10]
Immediately after saving a file when I check if it's there on the file system the file exists but it's empty. 

This is happening due to the fact that the save method resolves after the writeStream end event, but at that point the stream is not closed yet.

I'll be sending a PR for this I hope you have a chance to take a look.

**Comment by mojoaxel** [comment]
@alexgarcia9425 Can you please provide an example to reproduce this. Thanks!
