### ISSUE TITLE
Aw Snap. Out of Memory (Chrome)

### ISSUE THREAD

**Issue by TheMrBlackLord** [nbesli/pdf-merger-js#104]
I'm making my own React typescript application that combines PDF into one. I upload files using an `<input type="file">`. Then, by pressing the button, a function is called that combines them using this library:
```
let merger: PDFMerger = new PDFMerger()
...
const merge = async (e: FormEvent<HTMLFormElement>) => {
      e.preventDefault();
      setIsLoading(true);

      for (const file of files) {
         const buffer = await file.arrayBuffer();
         await merger.add(buffer);
      }

      await merger.save(saveName);
      merger = new PDFMerger();
      setIsLoading(false);
   }
```
I upload 8 files with a total size of 42.7 MB. After clicking the button, Сhrome starts using 3 GB of RAM, instead of the usual 200 - 700 MB, and an error window appears:
![image](https://user-images.githubusercontent.com/56202260/201483289-09a50523-0225-4c96-9477-a7e4ba91e64c.png)

**How to fix this error?**

**Comment by mojoaxel** [comment]
You would not try to methe such big files in the browser! I would recommend creating some kind of backend API to merge files on a big server.

What you can try is merging only one file after the other always using a new merger instance. But this is just a workaround that also would fail if files get even bigger.

**Comment by mojoaxel** [comment]
Also, you are using the same merger instance every time. Try moving the `new Merger` part also in the function.

**Comment by TheMrBlackLord** [comment]
At the end of function I create a new instance
