### ISSUE TITLE
I can't merge some pdf

### ISSUE THREAD

**Issue by joaosilva-lp** [nbesli/pdf-merger-js#110]
I have the following nodejs script:

```js
const fs = require('fs');
const PDFMerger = require('pdf-merger-js');

(async () => {
  const merger = new PDFMerger();

  fs.readdir('./', async (err, files) => {
    if (err) throw err;

    for (const file of files) {
      if (file.endsWith('.pdf')) {
        await merger.add(file);
      }
    }

    await merger.save('merged.pdf');
  });
})();

console.log('Finished');
```

The program works fine, however, if I try to merge like 2 pdfs exported from word with an invoice, the program can't merge the invoice, it should has some kind of protection. Is there any solution? Thanks for your work

**Comment by mojoaxel** [comment]
What error message does it show?
Maybe you could provide a pdf to reproduce this problem!?
