### ISSUE TITLE
Using raw buffer to add a pdf creates an Error

### ISSUE THREAD

**Issue by leo91000** [nbesli/pdf-merger-js#112]
If I give a raw PDF buffer to pdf merger, it gives me an error :

```log
The argument 'path' must be a string or Uint8Array without null bytes. Received Uint8Array(5044559)
```

Is it possible to pass directly a raw buffer to this lib ?

If no why the typescript definition indicates that we can use a Buffer as the `inputFile` argument ?

**Comment by mojoaxel** [comment]
There is actually a test to ensure `Uint8Array` inputs are supported:

https://github.com/nbesli/pdf-merger-js/blob/master/test/PDFMerger.test.js#L71-L84

@leo91000 Please check your code again and let us know if the problem still exists.
