### ISSUE TITLE
PDF scale/compress

### ISSUE THREAD

**Issue by MiBaWheels** [nbesli/pdf-merger-js#116]
Dear guys,

Is there a way to implement the "scale" funktion from pdf-lib? (https://pdf-lib.js.org/docs/api/classes/pdfembeddedpage#scale)

_Why?_ -> Because my merged PDF Documents are reaching an average file size of 1MB and that's too big to wrok with. 
Just trying to decrease the file size.
#61 and #31 are already questioned that, but now we are using PDF-Lib and I don't want to use ghostscript, like #31 did.

I'm also interested in other solutions. In my project I'm using Laravel and Vue.

**Comment by mojoaxel** [comment]
In general, if you are working with a php backend I would recommend merging the pdfs on the server using e.g. [PDFMerger](https://github.com/myokyawhtun/PDFMerger).

In my opinion "scaling" a pdf to reduce it's size is not the correct approach, and we will not implement it. This is just a merger library.

Sadly I have no idea why somtimes pdf get so big (#31). If this is an issue for you I see no other way as to use a much better pdf library like ghostscript.
