### ISSUE TITLE
Do we have support for secured PDFs on the browser version?

### ISSUE THREAD

**Issue by TrainedLoop** [nbesli/pdf-merger-js#120]
file exemple: https://uwaterloo.ca/onbase/sites/ca.onbase/files/uploads/files/samplesecured_256bitaes_pdf.pdf

Error:
Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways.

**Comment by Rusbelllozano** [comment]
Any update about this issue?

**Comment by mojoaxel** [comment]
encryptet pdfs are now also supported with the browser version (see 7a6a80ee6cb20dd32f44614107070354880ea2f3 and fa07f93757f1845b90acc7b1b622681a5b6f9af2).

Sadly there is still an issue with the provided [samplesecured_256bitaes_pdf.pdf](https://uwaterloo.ca/onbase/sites/ca.onbase/files/uploads/files/samplesecured_256bitaes_pdf.pdf): This still causes error. See #124 

@TrainedLoop If you still have issues with this pdf file and the new version (v4.3.1) of please open a new issue!
