### ISSUE TITLE
Merged pdf file size is twice as large as individual files

### ISSUE THREAD

**Issue by manofaria** [nbesli/pdf-merger-js#13]
Noticed this when merging two files about 36kb each, the merged file is 145kb.  The attached files are as follows: html_test_1.pdf and html_test_2.pdf are merged to create html_test_3.pdf.
[html_test_1.pdf](https://github.com/nbesli/pdf-merger-js/files/4233188/html_test_1.pdf)
[html_test_2.pdf](https://github.com/nbesli/pdf-merger-js/files/4233189/html_test_2.pdf)
[html_test_3.pdf](https://github.com/nbesli/pdf-merger-js/files/4233190/html_test_3.pdf)

**Comment by jonataspiazzi** [comment]
In a preliminar test I removed  
the line: this.doc.set Template(ext)
from:  _addEntireDocument
This fixed the issue. I not quite sure what this line do. I tested with a few pdf files, all works fine without this line and the size of the result is pretty much the sum of the original files.

**Comment by mojoaxel** [comment]
> I not quite sure what this line do.

https://github.com/rkusa/pdfjs/blob/master/docs/document.md#settemplateexternal-firstpageonly

I also think this line can be remove. 
@jonataspiazzi Feel free to provide a pull-request. Thx!
