### ISSUE TITLE
Is the wrong version uploaded at npm?

### ISSUE THREAD

**Issue by rnenjoy** [nbesli/pdf-merger-js#132]
I installed version 5 from npm but getting error on getInputAsBuffer-function. Which doesnt exist in the code in github at all.

Is the wrong version on npm or something?

**Comment by rnenjoy** [comment]
I'm sorry. I mean yarn, i install with yarn.

**Comment by mojoaxel** [comment]
@rnenjoy Could you please provide more details on that error and maybe even pdf files to reproduce this error. Thx!

**Comment by mojoaxel** [comment]
@rnenjoy Is this still an issue with the newest version?

**Comment by mojoaxel** [comment]
I'm closing this because it missing necessary context.

@rnenjoy Feel free to let us know if this is still an issue for you!
