### ISSUE TITLE
typescript error  when importing PDFMerger from esm module in node js application.

### ISSUE THREAD

**Issue by dhunganabibek** [nbesli/pdf-merger-js#136]
```import PDFMerger from "pdf-merger-js";```

This import in esm module gives a typescript error.

Module '"/Users/bibekdhungana/Programming/open-source/pdf-merger-test/node_modules/pdf-merger-js/index"' has no default export

![image](https://github.com/nbesli/pdf-merger-js/assets/51139940/767b0f6c-2e6e-4de7-a42a-99d972fdd5d4)

Link to code sandbox
https://codesandbox.io/p/live/69c640c0-9f51-4787-bcdd-8a8033d3131c

**Comment by izmaelmag** [comment]
I have the same issue. Dynamic imports doesn't work

**Comment by mojoaxel** [comment]
[A fix](/nbesli/pdf-merger-js/pull/137) by @dhunganabibek has been released as [v5.1.2](/nbesli/pdf-merger-js/releases/tag/v5.1.2) :rocket: 
Please let me know if this is still an issue.
