### ISSUE TITLE
How to save merged pdf to tmpdir?

### ISSUE THREAD

**Issue by jsdev13** [nbesli/pdf-merger-js#16]
Hey there,
please tell me if there is any chance to save the merged file to tmpdir.
Thank you.

**Comment by mojoaxel** [comment]
? just do something like this:
```js
await merger.save('/tmp/merged.pdf');
```

**Comment by jsdev13** [comment]
Awesome!
I actually had another issue with async-await on an express route and I thought that is caused by invalid parameter. 
You cand update readme.md at Code sample to "await merger.save('merged.pdf'); //save under given name **/ path**"
Your package is great!
Thank you. Cheers!

**Comment by mojoaxel** [comment]
> You cand update readme.md 

Feel free to provide a pull-request :wink:
