### ISSUE TITLE
To and '-' function did not work properly

### ISSUE THREAD

**Issue by 13samyakjain** [nbesli/pdf-merger-js#18]
when I used to function it returns invalid  parameters

**Comment by mojoaxel** [comment]
@13samyakjain Thanks for reporting this!
Could you please provide a sample so I can see how this is not working. Thanks!

**Comment by 13samyakjain** [comment]
Yes sure! I will sent it to you ASAP. I have also uploaded a solution for it in general folder

**Comment by 13samyakjain** [comment]
![WhatsApp Image 2020-05-27 at 9 25 40 PM (1)](https://user-images.githubusercontent.com/57790761/83043638-bad44700-a060-11ea-9080-152b685a50b1.jpeg)
![WhatsApp Image 2020-05-27 at 9 25 40 PM](https://user-images.githubusercontent.com/57790761/83043644-bd36a100-a060-11ea-9766-245848f4f9f5.jpeg)

This code may work sometimes.
Cause of error:- split function returns a string value(not a number).
A solution to the error:- Use of Number() to change span[0],span[1] to numerical value.

![WhatsApp Image 2020-05-27 at 9 33 41 PM](https://user-images.githubusercontent.com/57790761/83044451-d0963c00-a061-11ea-9d43-c41232c58147.jpeg)

As mentioned above, span is an array of strings,  which when uses span[0] returns a  string value to the _addFromToPage function, Same is followed for the '-' property.

**Comment by mojoaxel** [comment]
Looks like this is still an issue in v3.0.2
