### ISSUE TITLE
feat proposal: addAllFromFolder

### ISSUE THREAD

**Issue by sombreroEnPuntas** [nbesli/pdf-merger-js#24]
It would be convenient to add all files on a folder, like:

```js
  // const folder = "./test-folder/"
  addAllFromFolder(folder) {
    fs.readdirSync(folder).forEach((file) => {
      this._addEntireDocument(`${folder}${file}`)
    })
  }
```

**Comment by mojoaxel** [comment]
for now you could do something like this (untested):

```js
const glob = require('glob');

glob(FOLDER + '/*.pdf', {}, 
  (err, files) => 
    files.forEach(file => 
      merger.add(file)
    )
);
```

**Comment by mojoaxel** [comment]
This conflicts with browser support (#17). Because there is a [easy workaround](https://github.com/nbesli/pdf-merger-js/issues/24#issuecomment-650806856) I think we can close this.
