### ISSUE TITLE
Typescript Definition - npx tsc fails

### ISSUE THREAD

**Issue by nicolaselopez** [nbesli/pdf-merger-js#25]
I'm trying to use your library with typescript but it's failing throwing this error when i runt the npx tsc command:

`node_modules/pdf-merger-js/index.d.ts(6,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.`

This is because of the nested declares inside the index.d.ts that is not allowed on the newer versions of Typescript

**Comment by nicolaselopez** [comment]
I've just created the PR #26 that fixes this issue

**Comment by mojoaxel** [comment]
fixed with #26
