### ISSUE TITLE
Merged result PDF file is 3x bigger than expected

### ISSUE THREAD

**Issue by ngocdaothanh** [nbesli/pdf-merger-js#31]
Probably this problem is related to the memory problem mentioned in other issues.

I have 2 PDF files, 269KB and 23MB.

When I merge with Ghostscript, the result file is 20.4MB:
`gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -sOutputFile=ghostscript.pdf cover.pdf diary.pdf`

When I merge with pdf-merger-js, the result file is 59.4MB:

```js
const PDFMerger = require('pdf-merger-js')

const {COVER_PDF, DIARY_PDF, MERGED_PDF} = require('./config')

const merger = new PDFMerger()

const merge = async () => {
  merger.add(COVER_PDF)
  merger.add(DIARY_PDF)
  await merger.save(MERGED_PDF)
  console.log(`Saved ${MERGED_PDF}`)
}

merge()
```

Input files:
* [cover.pdf](https://drive.google.com/file/d/1r_Kz1Rlsl3TmLk6ahAxACNz7d0yOAwX_/view?usp=sharing)
* [diary.pdf](https://drive.google.com/file/d/10KytHNJKq5x2xRrAZs8UqFUqevFreCsw/view?usp=sharing)

Output files:
* [ghostscript.pdf](https://drive.google.com/file/d/1f2bvOsl_WkKKDyqxqbr1u1S2aQev_xfS/view?usp=sharing)
* [pdf-merger-js.pdf](https://drive.google.com/file/d/1RvICF5by4-ETPjROKikcP79nXpVSXaNA/view?usp=sharing)

**Comment by mojoaxel** [comment]
@ngocdaothanh Thanks for reporting this and for providing the pdf files. This is an issue that should be looked at!

**Comment by haveachin** [comment]
I have the same problem. My output file is **huge**!
The PDFs are from my university so I can't share them here.

![image](https://user-images.githubusercontent.com/30272106/104708416-f883fe00-571d-11eb-8099-2808ab2be461.png)

**Comment by dineshsbm** [comment]
I too have the same problem.
I have a requirement to merge 1000's of smaller chunk of PDF files into one big PDF file. The total size of all the files is ~181MB.
I verified with different plugins available out of which I am very much towards **pdf-merger-js** and **easy-pdf-merge** working fine. However I noticed the size of the merged PDF file is **~1GB in case of pdf-merger-js** whereas it is **~187MB when using easy-pdf-merge**.

**Comment by PendulousMind** [comment]
FYI I have repeated this issue within the pdfjs library.  Using either pdf-merger-js or pdfjs produced the exact same size file (699kb) from (165kb,11kb) files.

**Comment by mojoaxel** [comment]
Maybe a5177b4c4f578e818eb0cd3b5ccedeb201683e74 helps with this!? We should check if this is still an issue with v.3.3.2.

**Comment by hcramer** [comment]
I currently experiencing this issue as well with pdf-merger-js 3.4.0.

**Comment by afuller611-animas** [comment]
Any update on this or workarounds from anyone? I have two 5MB files that are becoming 183MB when merged. (On version 3.4.0)
