### ISSUE TITLE
Page Numbering of Merged PDF

### ISSUE THREAD

**Issue by himanshuj89** [nbesli/pdf-merger-js#36]
Hi, 

I am trying to merge couple of PDFs which has pagination respectively. For example - 

First PDF has paging like - 

- Page 1 of 3
- Page 2 of 3
- Page 3 of 3. 

Second PDF has paging like - 

- Page 1 of 2
- Page 2 of 2

When I merge these 2 PDFs, output PDF has paging like - 

- Page 1 of 3
- Page 2 of 3
- Page 3 of 3
- Page 1 of 2
- Page 2 of 2

Is it possible to have paging re-numbered on merge? 

thanks.

**Comment by mojoaxel** [comment]
This is out of scope of this library. You could try to change the resulting PDFs using e.g. [PDFs](https://www.npmjs.com/package/pdfjs).
