### ISSUE TITLE
Rename package to pdf-merger-js

### ISSUE THREAD

**Issue by mojoaxel** [nbesli/pdf-merger-js#4]
* [x] rename the repository
* [x] update the README
* [x] publish the new module

**Comment by mojoaxel** [comment]
@nbesli Could you please unpublish the old "pdf-merger-trvl" module:
```
npm unpublish pdf-merger-trvl -f`
```

**Comment by nbesli** [comment]
> @nbesli Could you please unpublish the old "pdf-merger-trvl" module:
> 
> ```
> npm unpublish pdf-merger-trvl -f`
> ```

Done, old package status is changed as deprecated

**Comment by mojoaxel** [comment]
Thx!
