### ISSUE TITLE
Merge Compressed PDF gives error

### ISSUE THREAD

**Issue by Nikita747** [nbesli/pdf-merger-js#42]
TypeError: Cannot read property 'compressed' of undefined

**Comment by mojoaxel** [comment]
@Nikita747 Can you please provide an example or at least some more information on how to reproduce this!?

**Comment by romainwurtz** [comment]
This sample file created by DocRaptor seems to crash every time.

[doc-194199933.pdf](https://github.com/nbesli/pdf-merger-js/files/6621414/doc-194199933.pdf)

```
const PDFMerger = require('pdf-merger-js');

(async () => {
    const test = new PDFMerger();
    test.add('doc-194199933.pdf');
    await test.saveAsBuffer(); // crash
})();
```

**Comment by mojoaxel** [comment]
This is a pdfjs-bug, that is tracked here: https://github.com/rkusa/pdfjs/issues/265

**Comment by dallen-baldwin-horrocks** [comment]
I ran into this today after implementing merging to fix another issue with external PDFs... @mojoaxel have you seen [this ](https://github.com/rkusa/pdfjs/issues/265#issuecomment-976622488) response and considered implementing it? It looks like it would probably break the browser capabilities of the package... but it would at least be something.

**Comment by mojoaxel** [comment]
@dallen-baldwin-horrocks The provided "solution" adds an external dependency to pdf-toolkit which needs native bindings. 
Feel free to use node-pdftk to merge you pdfs but this project aims to be pure JavaScript for compatibility purposes.

**Comment by dallen-baldwin-horrocks** [comment]
That's understandable. I may have to do that anyways since I ran into another upstream pdfjs issue within 5 minutes of composing that last message...

**Comment by ajitStephen** [comment]
https://stackoverflow.com/a/63208646/5518625 

alternative solution 👆🏻
