### ISSUE TITLE
PDFs aren't merged in order

### ISSUE THREAD

**Issue by poPaTheGuru** [nbesli/pdf-merger-js#62]
Hello!

This is my code:

```
const LazyDownloadPDFButton = (number, date, totalHours, formattedHours) => (
        <Button
            className={classes.download}
            onClick={
                async () => {
                    const doc = <InvoicePDF number={number} date={date} totalHours={totalHours} formattedHours={formattedHours} />
                    const asPdf = pdf()

                    asPdf.updateContainer(doc)

                    const initialBlob = new Blob([fileRef.current.files[0]], { type: 'application/pdf' })
                    const appendixBlob = await asPdf.toBlob()

                    let merger = new PDFMerger()
                    await Promise.all([initialBlob, appendixBlob].map(async (file) => await merger.add(file)))

                    const mergedPdf = await merger.saveAsBlob()
                    // merger = null
                    saveAs(mergedPdf, `SM${number}.pdf`)
                }}
        >
            Download
        </Button>
    )
```

No matter the order in the `map` function, the PDFs are always merged as `appendixBlob` and then `initialBlob`. 

I tried to change the order in array, but it merges them the same. 

Did I do something wrong? 

-------------------------------

**EDIT**

After some testing, it turns out that sometimes in merges them in order of the array, but sometimes no. I found that it doesn't matter which one is bigger or smaller. 

Can i achieve the same order everytime?

**Comment by Prinzhorn** [comment]
`merger.add` is synchronous, you don't need to `await` it. It appears by using `Promise.all` the way you did you introduce a race condition, because both calls happen concurrently.
