### ISSUE TITLE
Failed to execute 'readAsArrayBuffer' on 'FileReader'

### ISSUE THREAD

**Issue by stivncastillo** [nbesli/pdf-merger-js#63]
I had this error: 

`TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.`

react:

    const merger = new PDFMerger();
    await merger.add("https://github.com/nbesli/pdf-merger-js/blob/master/test/fixtures/MergeDemo.pdf")

**Comment by mojoaxel** [comment]
@DanMHammer Could you maybe have a look at this!?

**Comment by Prinzhorn** [comment]
Shouldn't you get this?

> Access to fetch at 'https://github.com/nbesli/pdf-merger-js/blob/master/test/fixtures/MergeDemo.pdf' from origin '....' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> TypeError: Failed to fetch

From this line https://github.com/nbesli/pdf-merger-js/blob/master/browser.js#L46

The FileReader code path should never be reached.

**Comment by mojoaxel** [comment]
@stivncastillo Please check if this is still an issue with [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).

**Comment by mojoaxel** [comment]
Closing as solved with #84. Please let us know if this is still an issue!
