### ISSUE TITLE
Make `add` async for the non-browser version as well

### ISSUE THREAD

**Issue by Prinzhorn** [nbesli/pdf-merger-js#66]
When using this library on a server currently every `add` call will lock up your process because of `readFileSync`. It'd be great to make this async as well. Would also align browser and node version more closely.

```
import { readFile } from 'fs/promises';
```

https://nodejs.org/api/fs.html#fs_promises_api

Edit: I didn't look to closely into it, but maybe `index.js` and `browser.js` could also inherit from a base class. They share things like `_resetDoc` and the entire ` _addFromToPage` logic etc. They only differ in the way files are read/write.

**Comment by mojoaxel** [comment]
this is was implemented in [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).
