### ISSUE TITLE
Error: Invalid PDF: startxref not found

### ISSUE THREAD

**Issue by scorpioRED** [nbesli/pdf-merger-js#69]
Hi! Got error **Error: Invalid PDF: startxref not found**
What does it mean?

**Comment by mojoaxel** [comment]
@scorpioRED Could you please provide the pdf that resulted in this error!?

**Comment by scorpioRED** [comment]
Unfortunately, I can not send it, this is a passport.
If I run the once - it's ok, but in express server - got this error

**Comment by scorpioRED** [comment]
I don't understand why it doesn't work with express

**Comment by Jossic** [comment]
I have the same problem

here's my console 
![image](https://user-images.githubusercontent.com/60156884/145293196-245b4524-d90e-4904-a426-9ec329ec6b96.png)

The data I try to merge
![image](https://user-images.githubusercontent.com/60156884/145293269-1e137774-58e0-490a-a9b0-a294b6be8c65.png)

And the function 
![image](https://user-images.githubusercontent.com/60156884/145293305-abdd93b1-eb68-4aac-8143-5c47c90c9dfd.png)

**Comment by Jossic** [comment]
Hello, 

I found the solution @scorpioRED .

It seams to appeared when one of the fetched files is unavailable, or corrupted, so it's indeed Invalid PDF...
Maybe you could try with only 2 corrects files and check if it's working...

Thanks !

**Comment by mojoaxel** [comment]
Looks to me like a problem of pdfjs with some (potentional broken) pdfs.
If anybody could provide some some pdf-files to reproduce this issue it might be worth opening an issue in the pdfjs repository.

**Comment by urjit2498** [comment]
I'm facing same issue. Can anyone find the solution regarding the same????

I am using pdf buffers for merging the pdf.

**Comment by mojoaxel** [comment]
@scorpioRED @urjit2498 Please check if this is still an issue with [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).

**Comment by mojoaxel** [comment]
closing as solved with #84. Please let us know if this is still an issue!
