### ISSUE TITLE
Push a new release: `browser.d.ts` is not available in 3.2.1

### ISSUE THREAD

**Issue by TristanTouchain** [nbesli/pdf-merger-js#71]
Hi everyone,

Do you think that a new release is possible? 
I need the `browser.d.ts` file but since the last release 3.2.1, some changes in master is not available. Is it normal?

Have a nice day!

**Comment by mojoaxel** [comment]
:tada:  https://github.com/nbesli/pdf-merger-js/releases/tag/v3.3.0
