### ISSUE TITLE
Link to page broken after merging

### ISSUE THREAD

**Issue by ratchet34** [nbesli/pdf-merger-js#76]
Hi,

One of my document contains links to different pages of itself and after merging those links no longer work anymore. URL links work well though.
Those links are generated by jsPDF with the following code : 
`doc.textWithLink('Link', 2, 2, { pageNumber: 3 });`

**Comment by gmantaos** [comment]
I can also confirm that links break for documents generated with puppeteer.

**Comment by mojoaxel** [comment]
Thanks for reporting this!
If you provide a very basic example-pdf we create an issue at [jsPDF](https://github.com/parallax/jsPDF).
Also feel free to open a issue yourself describing the problem. Don't forget to link back to this issue, here. Thx!

**Comment by mojoaxel** [comment]
@ratchet34 @gmantaos Please check if this is still an issue with [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).

**Comment by mojoaxel** [comment]
Closing as solved with #84. Please let us know if this is still an issue!
