### ISSUE TITLE
Pdf & Jpg Merge

### ISSUE THREAD

**Issue by Debajyoti14** [nbesli/pdf-merger-js#90]
Can i merge pdf alongside jpg here
because for me when i merge multiple pdf, it works nicely
but if i combine it with jpg it doesn't work.

Any fix???

**Comment by Furkangunduz** [comment]
I think it would be great. 
@mojoaxel do you guys planning to add this feature to the project ? 
If you're planning it, I can work on it.

**Comment by mojoaxel** [comment]
I don't think we should add the functionality to merge other file formats (e.g. images) here.
I would recommend generating pdf from the images first or even use pdf-lib directly to generate and merge mixed content.
