### ISSUE TITLE
saveAsBuffer() returns a Uint8Array instead of a Buffer

### ISSUE THREAD

**Issue by t0m4-null** [nbesli/pdf-merger-js#93]
Since v4.0.0 (and pdf-lib replacing pdfjs), saveAsBuffer() method returns a Uint8Array instead of a Buffer.

So, to fix it, I had to replace `await merger.saveAsBuffer()` with `Buffer.from(await merger.saveAsBuffer())`

**Comment by mojoaxel** [comment]
@t0m4-null Yeah, that is a bug, introduced by #84

I'll provide a fix, soon.
