### ISSUE TITLE
Merging pdfs in a loop results in a blank page

### ISSUE THREAD

**Issue by jerry-flam** [nbesli/pdf-merger-js#98]
I am using the following code to merge the pdfs of a folder, inspired from this comment: https://github.com/nbesli/pdf-merger-js/issues/24#issuecomment-650806856

```javascript
const path = require('path');
const glob = require('glob');
const PDFMerger = require('pdf-merger-js');

const merger = new PDFMerger();
const pdfsFolder = path.join(__dirname, 'files');

glob(pdfsFolder + '/*.pdf', {}, (_err, files) => {
  files.forEach((file) => {
    merger.add(file);
  });
  merger.save('merged.pdf');
});
```

The result is an empty pdf file.

On the other hand, the following works fine: 
```javascript
const PDFMerger = require('pdf-merger-js');

const merger = new PDFMerger();
const pdfsFolder = path.join(__dirname, 'files');

(async () => {
  await merger.add(pdfsFolder + '/file1.pdf');
  await merger.add(pdfsFolder + '/file2.pdf');
  await merger.save('merged.pdf');
})();
```

Am I missing something or it is a bug?

**Software versions:**
_node: v16.17.0
glob: v8.0.3
pdf-merger-js: v4.1.0_

**Comment by jerry-flam** [comment]
Here is a repo reproducing the issue: https://github.com/jerry-flam/pdf-merger-js-issue-98

**Comment by mojoaxel** [comment]
I had a quick look. It looks to me like you forgot to await the `add` promise.

Try this:

```js
glob(pdfsFolder + '/*.pdf', {}, (_err, files) => { 
for (let file of files) { 
  await merger.add(file);
});
merger.save('merged.pdf'); });
````

**Comment by jerry-flam** [comment]
Thank you very much! This solved it!
